version: '3.9'

services:
  node:
    image: node:lts-slim
    working_dir: /app
    env_file:
      - .env
    command: /bin/sh -c 'npm install && npm start'
    ports:
      - '3030:3030'
    volumes:
      - ./src:/app
    depends_on:
      - db

  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db:/data/db
